language: java
install: true

jdk:
- openjdk11

before_script:
- cd oml-tools

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true
      branch: master
