language: java
install: true

jdk:
- oraclejdk8

before_script:
- cd io.opencaesar.oml2bikeshed

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      repo: opencaesar/oml-bikeshed
      branch: master